name: .NET Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Clonando o repositório e trocando a branch
      uses: actions/checkout@v4

    - name: Instalando .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Instalando dependências
      run: dotnet restore
      working-directory: ./MusicaAPI

    - name: Compilando o projeto
      run: dotnet build
      working-directory: ./MusicaAPI
    
    - name: Test
      run: dotnet test
      working-directory: ./MusicaAPI.Tests